### ISSUE TITLE
2023.6.1 报错无法使用，求助~

### ISSUE THREAD

**Issue by WalterDSU** [shaonianzhentan/xiaomi_radio#7]
Logger: homeassistant.loader
Source: custom_components/xiaomi_radio/media_player.py:236
Integration: 小米电台 ([documentation](https://github.com/shaonianzhentan/xiaomi_radio))
First occurred: 14:18:40 (2 occurrences)
Last logged: 14:40:50

Unexpected exception importing platform custom_components.xiaomi_radio.media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_radio/media_player.py", line 234, in <module>
    class AacConverter(HAFFmpeg):
  File "/config/custom_components/xiaomi_radio/media_player.py", line 236, in AacConverter
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

**Comment by shaonianzhentan** [comment]
😂都更新那么快的吗，等我升到6月份版本了再修

**Comment by WalterDSU** [comment]
大佬的集成有几个还有问题. 你升级就知道. 我就不一一提issue. 辛苦了.

**Comment by WalterDSU** [comment]
大佬这个错误, 还有计划更新吗?

**Comment by shaonianzhentan** [comment]
我太忙了，没时间修这个BUG，欢迎提交PR

**Comment by shaonianzhentan** [comment]
已修复
